### ISSUE TITLE
Some initial issues

### ISSUE THREAD

**Issue by demlak** [S1SYPHOS/kirby-lingonberry#1]
Hi,
just installed the theme for a test.. looks nice.. thx a lot
but there are some initial problems:
1. pluginfolders "images" and "quickselect" are empty
2. you need a user called "admin" to get started with pre-defined testposts. this would be a nice info at the readme.

since i'm not familiar with github, i don't know how to submit this beside this issue report.. so i'm sorry for this way of submission. but i think it will be helpfull.

thx

**Comment by S1SYPHOS** [comment]
Hey there,
thank you for letting me know! I just released the code also running for the demo. If you want to get started right away, you should empty the content folder, anyway, but I'll make that clearer.

Fixing the empty plugin repos is a breeze, they're just git repos on my local machine.

**Comment by S1SYPHOS** [comment]
It has been taken care of 💃
