### ISSUE TITLE
Alt attribute handling

### ISSUE THREAD

**Issue by texnixe** [S1SYPHOS/kirby-lingonberry#10]
```
<img src="<?= $image->resize(766, null, 85)->url() ?>"<?php e($image->alt()->isNotEmpty(), ' alt="' . $image->alt()->html() . '"') ?>>
```
If the alt field is empty, the image will not have an alt attribute. However, the alt attribute should always be present even if empty for accessibility reasons.

**Comment by S1SYPHOS** [comment]
Thank you for letting me know.
