### ISSUE TITLE
Making Gravatar support optional

### ISSUE THREAD

**Issue by demlak** [S1SYPHOS/kirby-lingonberry#11]
Hi,
an option to disable gravatar support (comments-area), would be nice.

thx

**Comment by S1SYPHOS** [comment]
What do you have in mind for people disabling it, showing a (locally saved) 'incognito' avatar?

**Comment by demlak** [comment]
maybe a default locally saved incognito avatar is the best solution. maybe changing layout by just not providing any avatar, looks better.

i'm undecided =)

**Comment by S1SYPHOS** [comment]
Two options:
- integrating [`$user->avatar()`](https://getkirby.com/docs/cheatsheet/user/avatar) for registered people, serve standard image for the rest OR
- serve standard image for all (which may be defined in `config.php`)

I've decided to go for the latter right now, and if I got time to spare in the future, I'll look into the first one. Thanks for letting me know, anyway.
