### ISSUE TITLE
no blog entries - error with site/templates/home.php?

### ISSUE THREAD

**Issue by demlak** [S1SYPHOS/kirby-lingonberry#13]
Hi,
the last update of ```site/templates/home.php``` killed the frontpage.

old version works for me to show blog posts on first page. but pagination still does not work on other pages.

**Comment by S1SYPHOS** [comment]
Stay with the old one then, I'll look into it soon.
Thank you!

**Comment by S1SYPHOS** [comment]
This should be fixed now, any feedback is welcome!

**Comment by demlak** [comment]
seems to work perfect, thx a lot
