### ISSUE TITLE
RSS-Feed does not Include Intro - fix inside

### ISSUE THREAD

**Issue by demlak** [S1SYPHOS/kirby-lingonberry#16]
Currently, the rss-feed does only include the text field.
In most cases, this will split the intention of a blog post on the rss feed. 

To include Intro field on demand, in `site/plugin/feeds/template.php` change the following line:
``` php
<description><![CDATA[<?php echo $item->{$textfield}()->kirbytext() ?>]]></description>
```
to
``` php
<description><![CDATA[<?php if($item->intro()): ?><?php echo $item->intro()->kirbytext() ?><?php endif ?><?php echo $item->{$textfield}()->kirbytext() ?>]]></description>
```
#19

**Comment by S1SYPHOS** [comment]
Fixed.
