### ISSUE TITLE
table alignment - unwanted behavior

### ISSUE THREAD

**Issue by demlak** [S1SYPHOS/kirby-lingonberry#20]
hi,
i tried to generate some tables with alignment. i need several tables wich are aligned on cells, that are at the same size. In the following example all cells on the 3rd column are all the same size. i tried to align them to the right site. the cells on the 2nd column should now align on the right site. the collumn should have exactly all the same distance to the 3rd column, but they don't. The distance seems to depend on the width of the 2nd column/cell

example 1 markdown:
``` markdown
|Table Header 1|Table Header 2|Table Header 3|
|---|---:|---:|
|Division 1|Division 2|Division 3|
|Division 1|Division 2|Division 3|
|Division 1|Division 2|Division 3|


|Table Header 1|Table Header 2|Table Header 3|
|---|---:|---:|
|Division 1|Divisifdsgfdsgon 2|Division 3|
|Dividsadsadsadsadassion 1|Divisgfdsgfdsgsion 2|Division 3|
|Division 1|Divfdsgfdision 2|Division 3|


|Table Header 1|Table Header 2|Table Header 3|
|---|---:|---:|
|Division 1|Division 2|Division 3|
|Division 1|Divisfdsgfdsgion 2|Division 3|
|Divisdsadsadsadsadasdion 1|Divisfdsgfdggfdgfdgion 2|Division 3|
```
example 1 picture:
![example-mr](https://user-images.githubusercontent.com/11285006/36149956-15fa2a9a-10c2-11e8-9c24-4e73d0be8139.jpg)

In the 2nd example i tried to align the 2nd column to the left, where all cells of the 1st colum are all the same size. a similar effect happens. again, the column alignment seem to depend on the column width.

example 2 markdown
``` markdown
|Table Header 1|Table Header 2|Table Header 3|
|:---|:---|---:|
|Division 1|Divisiodsafdsafdsn 2|Division 3|
|Division 1|Division 2|Divisiofdsafdsafdsn 3|
|Division 1|Division 2|Division 3|

|Table Header 1|Table Header 2|Table Header 3|
|:---|:---|---:|
|Division 1|Divisidsfdsfon 2|Division 3|
|Division 1|Divisfdsafdsfion 2|Division 3|
|Division 1|Division 2|Divisdsfdion 3|

|Table Header 1|Table Header 2|Table Header 3|
|:---|:---|---:|
|Division 1|Division 2|fdsf 3|
|Division 1|Division 2|Division 3|
|Division 1|Dividfsfdssion 2|Division 3|
```

example 2 picture:
![example-ml](https://user-images.githubusercontent.com/11285006/36149881-c412e758-10c1-11e8-8925-e20143745500.jpg)

Since i don't know if this is a problem on kirby itself or on the lingonberry theme, i just started in here, before i head over to the getkirby forum, if necessary.

thx in advance

**Comment by S1SYPHOS** [comment]
You are right insofar as alignment depends on content width. However, you may change this bevahiour with `table-layout: fixed` - for more information, see this [excellent article](https://css-tricks.com/fixing-tables-long-strings) on the subject, as well as its more general [follow-up](https://css-tricks.com/almanac/properties/t/table-layout) on CSS-Tricks.

Browser support is [very nice](https://caniuse.com/#search=table-layout), too.
