### ISSUE TITLE
missing /assets/images/2x/post-formats/image.png

### ISSUE THREAD

**Issue by demlak** [S1SYPHOS/kirby-lingonberry#9]
Hi,
jquery.js wants to load /assets/images/2x/post-formats/image.png but this file does not exist.

greetings

**Comment by S1SYPHOS** [comment]
Thanks for your report, this should be fixed now! Just rename `assets/images/2x/post-formats/image-gallery.png` to `image.png`.

I've also forwarded this issue to Anders Norén, since this occurs in the original Wordpress theme as well.
